// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
    public static void main(String[] args) {   
        String Num = args[0];
        int n = Integer.parseInt(Num);
        int countGreater = 0; 
        int countLessOrEqual = 0; 
        for (int i = 0; i < n; i++) { 
            double rnd = Math.random();
            if (rnd > 0.5) { 
                countGreater++;
            } else {
                countLessOrEqual++;
            }
        }
        System.out.println("> 0.5: " + countGreater + " times");
        System.out.println("<= 0.5: " + countLessOrEqual + " times");
        if (countLessOrEqual > 0) {
            double ratio = (double) countGreater / countLessOrEqual;
            System.out.println("Ratio: " + ratio);
    }
	}
}